### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by Ankso** [Ankso/TrinityCore#1]
## Primary tasks:
- [ ] Conquerable zones system:
  - [x] Claim/unclaim/conquest territories.
  - [x] NPC interactuation only available to the territory owners.
    - [x] Daily quests.
    - [x] Traders and services.
    - [x] Special profession NPCs.
  - [ ] Spawn more resources/rare materials.
  - [x] Set the level of the mobs to 40 or lower.
- [x] Inventory/equipment/gold drop/loot system on player death.
- [x] Limit map regions.
- [x] Unbind [almost] all items (to soul).
- [x] New character's spawns.
  - [x] Proper intro quests for Alliance/Horde.
  - [x] Teleport players to correct location after intro.
- [x] Gold bank (for players).
- [x] Taxi paths (limit/remove).
- [x] Limit ships and Zepelins to allowed regions.
- [ ] Test high level dungeons.
- [ ] Lower the required level for Azshara quests.
- [x] Make leveling exponentially faster from level 10 upwards.
- [ ] Custom recipes for professions via NPC quests.
- [x] Allow enter on BGs/Arenas only with certain set equipped.
### Secondary tasks (after release):
- [ ] Create new quests in Azshara according to the new lore.
- [ ] Barricades for null-sec.
- [ ] Drop the level of the guards to 40.
- [ ] Mage portals.
- [ ] Move/spawn important NPCs that are outside the limited game zone.

**Comment by Ankso** [comment]
A couple more things done in baea293dcdd813f11fed71a5b6f246a14dd2e413

**Comment by Ankso** [comment]
More in https://github.com/Ankso/TrinityCore/commit/4def98b0379df2725e10178f3784797b9c2f9297
